### PR TITLE
Allow Zxcvbn to be loaded asynchronously

### LINKED ISSUE #1: How can we async load zxcvbn?
Would be nice to have a way to load this script asynchronously with the app rather than bundling it at compile time, since it's a hefty 3-600 kb (depending on gzip vs uncompressed).
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27741630-how-can-we-async-load-zxcvbn?utm_campaign=plugin&utm_content=tracker%2F25038149&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F25038149&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jrjohnson**
Provides a second `async-password-strength` shim which loads zxcvbn on
demand. This allows the very heavy zxcvbn to be loaded only when it is
needed.

Adds a build option bundleZxcvbn which defaults to true to maintain the
current behavior. When this option is set to false zxcvbn will not be
bundled into the apps `vendor.js` file.

I'm not 100% sure about this approach. There are three things in particular that I don't like:
1) I have added `RSVP` as an AMD module dependency and then I'm using `RSVP.default.Promise` I had not idea if this is supported or not. It works for me, but should probably be tested.
2) `zxcvbn.js` expects to be found at the root level `/zxcvbn.js`. I don't think there is a way to get the `rootURL` configuration option at the point of creating this shim so I'm not sure there is a reasonable way to work around this. Again - works for me - but is this an OK compromise?
3) I don't know anything about fastboot except that I'm certain that `document` isn't going to be available in that context.

Aside from number 1 I think just documenting these cases and advising against using the async loader is sufficient, but I'm open to any input or ways to mitigate these issues.

There is an entirely different path we can take to do this work. It requires exposing a service instead of the shim here. It is kind of a radical departure from the way this addon currently works, but I did some preliminary work in that direction and it is doable, but it does change the current API drastically so it may be better to do that *after* this is released to provide a smoother upgrade path to what will be a breaking change.

Fixes #1

### CODE REVIEW

**Comment by elwayman02** [comment]
This seems like a great interim step, and I'm definitely in favor of abstracting this away via a service interface instead of the shim. Nice work!

**Comment by JoshSmith** [comment]
@jrjohnson @elwayman02 take a look at this PR as a good example, too: https://github.com/code-corps/ember-stripe-service/pull/59/files

**Comment by jrjohnson** [comment]
@JoshSmith for doing this as a service? Yes. That is a good next step, thanks for the code.

**Comment by st-h** [comment]
this worked fine for me in development mode. Then I used a local nginx to serve the production build and I ended up with the following error
```vendor.js:3478 Uncaught SyntaxError: Unexpected token .```
which references this line:
`` `/zxcvbn.js`,t.src="/zxcvbn.js",t.type="text/javascript",t.async=!0``

Regarding some of the other points I have to say that it feels like the current api is just not meant to work asynchronously in an ember context. For instance one would expect to be able to resolve `strength.score` within a template, however it seems like the provided promise only provides a plain js object which does not play well with embers conventions. Maybe I am overlooking something, but this has been the only method I could find to reliably render the score
``` 
  strength: function() {
    return strength(this.get('changeset.password')).then((s) => {
      this.set('score', s.score);
    });
  }.observes('changeset.password'),
```
Considering that loading ~400k is quite an impediment for most apps (except only internally used ones), I am wondering who would actually be willing to load that amount of data all the time just to display a hint for instantly updating password hints or requirements, which is only rarely accessed in common types of apps. So, to me it seems we might be better off to design a nice promise based api that works asynchronously and give people the option to do things sync (if that actually even is a use case after all). Even though this implies another major release, which breaks backwards compatibility.

**Comment by jrjohnson** [comment]
@st-h confirmed I'm seeing the same issue on a production build. Good catch! Thanks for testing that. This may mean going back to the drawing board and moving straight to a service after all.

**Comment by JoshSmith** [comment]
Great work testing @st-h.

**Comment by elwayman02** [comment]
I'm definitely in favor of the service approach!

**Comment by jrjohnson** [comment]
Alright. Given that I can’t figure out a fix for the prod AMD module issue I’m going to close this and go with a service instead. I wrote most of that code already anyway so I should be able to clean it up and get a PR in tonight or tomorrow.

**Pull request closed without merging**
